name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - uses: gradle/gradle-build-action@v2
    - run: gradle assembleRelease

    - uses: actions/upload-artifact@v3
      with:
          name: github-${{ github.sha }}
          path: app/build/outputs/apk/github/release/*.apk
    - uses: actions/upload-artifact@v3
      with:
          name: fdroid-${{ github.sha }}
          path: app/build/outputs/apk/fdroid/release/*.apk
      
